name: Release and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      prs: ${{ steps.release.outputs.prs }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      manager-server--tag-name: ${{ steps.release.outputs.folder--tag-name }}
      ips-syncer--tag-name: ${{ steps.release.outputs.folder-a--tag-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: python

  artifacts:
    runs-on: arc-generic
    needs:
      - release-please

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Docker Push
        env:
          FOLDER_TAG: ${{ needs.release-please.outputs.manager-server--tag-name }}
          FOLDER_A_TAG: ${{ needs.release-please.outputs.ips-syncer--tag-name }}
        run: |
          echo $FOLDER_TAG
          echo $FOLDER_A_TAG
