name: Release and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      prs: ${{ steps.release.outputs.prs }}
      paths: ${{ steps.release.outputs.paths_released }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      manager-server--tag-name: "${{ steps.release.outputs.folder--tag-name }}"
      ips-syncer--tag-name: "${{ steps.release.outputs.folder/a--tag-name }}"
      manager-server--version: "${{ steps.release.outputs.folder--version }}"
      ips-syncer--version: "${{ steps.release.outputs.folder/a--version }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: python

  artifacts:
    runs-on: ubuntu-latest
    needs:
      - release-please

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Docker Push
        env:
          CREATED: ${{ needs.release-please.outputs.releases_created }}
          FOLDER_TAG: ${{ needs.release-please.outputs.manager-server--tag-name }}
          FOLDER_A_TAG: ${{ needs.release-please.outputs.ips-syncer--tag-name }}
          FOLDER_VERSION: ${{ needs.release-please.outputs.manager-server--version }}
          FOLDER_A_VERSION: ${{ needs.release-please.outputs.ips-syncer--version }}
          PATHS: ${{ needs.release-please.outputs.paths }}
        run: |
          echo $CREATED
          echo $FOLDER_TAG
          echo $FOLDER_A_TAG
          echo $FOLDER_VERSION
          echo $FOLDER_A_VERSION
          echo $PATHS
